name: mad_final_project
description: "A RealEstate Application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  dio: ^5.9.0
  connectivity_plus: ^7.0.0
  logger: ^2.6.2
  pinput: ^6.0.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  hive_flutter: ^1.1.0
  flutter_svg: ^2.2.2
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/lotties/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
